services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: kris20204/research-navigator-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/paperiq}
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    image: kris20204/research-navigator-frontend:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"

volumes:
  mongo_data:
